# Generated by Django 3.2.18 on 2023-03-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imgage',
            new_name='image',
        ),
    ]
