# Generated by Django 3.2.13 on 2023-04-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movies',
            new_name='movie',
        ),
    ]
