# Generated by Django 3.2.18 on 2023-03-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updtated_at',
            new_name='updated_at',
        ),
    ]
