# Generated by Django 3.2.18 on 2023-04-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_release_data_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tile',
            new_name='title',
        ),
    ]
